#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  protocon
#
#  Copyright 2017 Spencer McIntyre <zeroSteiner@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

import argparse
import functools
import os
import sys

import boltons.iterutils
import boltons.urlutils
import pluginbase

get_path = functools.partial(os.path.join, os.path.abspath(os.path.dirname(__file__)))
sys.path.append(get_path('lib'))

import protocon

def main():
	plugins = pluginbase.PluginBase(package='protocon.plugins').make_plugin_source(
		searchpath=[get_path('lib', 'protocon', 'plugins')]
	)
	connection_drivers = {}
	epilog = 'target_url examples:\n'
	for plugin in plugins.list_plugins():
		module = plugins.load_plugin(plugin)
		if not hasattr(module, 'ConnectionDriver'):
			continue
		connection_drivers[plugin] = module.ConnectionDriver
		for example in module.ConnectionDriver.examples.values():
			epilog += "  {0}\n".format(example)

	parser = argparse.ArgumentParser(description='ProtoCon', conflict_handler='resolve', formatter_class=argparse.RawTextHelpFormatter)
	parser.add_argument('-q', '--quiet', action='store_true', default=False, help='initialize quiet to True')
	parser.add_argument('-v', '--version', action='version', version='%(prog)s Version: ' + protocon.__version__)
	parser.add_argument('target_url', help='the connection URL')
	parser.add_argument('scripts', metavar='script', nargs='*', help='the script to execute')
	parser.epilog = epilog
	arguments = parser.parse_args()

	url = boltons.urlutils.URL(arguments.target_url)

	protocon.print_status("Loaded {0} connection drivers".format(len(connection_drivers)))
	driver = next((driver for driver in connection_drivers.values() if url.scheme in driver.schemes), None)
	if driver is None:
		protocon.print_error('No connection driver for scheme: ' + url.scheme)
		return os.EX_USAGE
	for attribute in driver.url_attributes:
		if not getattr(url, attribute):
			protocon.print_error('Missing required URL attribute: ' + attribute)
			return os.EX_USAGE

	driver = driver(url)
	engine = protocon.Engine(driver, quiet=arguments.quiet)
	for script in arguments.scripts:
		if engine.do_load(script):
			break
	else:
		engine.cmdloop()

	engine.connection.close()
	return 0

if __name__ == '__main__':
	sys.exit(main())
